export const branding = {
  applicationName: "GOGA Receipt Automation System",
  shortName: "GOGA",
  organization: "Gayaza Old Girls Association (GOGA)",
  organizationShort: "Gayaza Old Girls Association",
  tagline: "Official Receipt Automation & Payment Management System",
  loginSubtitle: "Official Receipt Automation & Payment Management Platform",
  description:
    "Official Receipt Automation and Payment Management System for Gayaza Old Girls Association (GOGA).",
  author: "Gayaza Old Girls Association",
  publisher: "Gayaza Old Girls Association",
  keywords: [
    "GOGA",
    "Gayaza Old Girls Association",
    "Gayaza High School",
    "Receipt Automation",
    "Payment Management",
    "Membership",
    "Uganda"
  ],
  themeColor: "#BE1E2D",
  logo: {
    src: "/goga-logo.png",
    alt: "Gayaza Old Girls Association (GOGA) official logo"
  },
  social: {
    title: "Gayaza Old Girls Association (GOGA)",
    description: "Official Receipt Automation & Payment Management System.",
    imagePath: "/og-image.png"
  },
  pwa: {
    name: "GOGA",
    shortName: "GOGA",
    description:
      "Official Receipt Automation System for Gayaza Old Girls Association."
  },
  dashboard: {
    welcomeTitle: "Welcome to the GOGA Receipt Automation System",
    welcomeSubtitle: "Gayaza Old Girls Association"
  },
  footer: {
    poweredByLabel: "Powered by",
    copyright: (year: number) =>
      `© ${year} Gayaza Old Girls Association (GOGA). All Rights Reserved.`
  },
  emailDisclaimer:
    "This is an automated email generated by the official GOGA Receipt Automation System.",
  receiptFooter:
    "This receipt was electronically generated by the GOGA Receipt Automation System."
} as const;

export function getCopyrightText(year = new Date().getFullYear()): string {
  return branding.footer.copyright(year);
}
